GET http://localhost:3000/customer/fsdfadf12321


###
POST http://localhost:3000/user/create 
Content-Type: application/json 

{
    "username": "Munesh1",
    "role": "customer"
}

###
GET http://localhost:3000/user/6585b63b3de87b930e1dff5c